name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]    
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix- 
    - uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
            ${{ runner.os }}-build-
    - name: Install dependencies
      run: mix deps.get
    - name: Run warnings errors
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
    - name: Run format
      run: mix format --check-formatted
    - name: Run credo
      run: mix credo
